fix maybe-uninitialized
My compiler throwed the error:
gcc -Os -fomit-frame-pointer -Wall -Wextra -Wno-unused-parameter -Werror -Iinc -o bcal src/bcal.c -lreadline
src/bcal.c: In function 'strtouquad':
src/bcal.c:401:15: error: 'multiplier' may be used uninitialized in this function [-Werror=maybe-uninitialized]
    val = (val << multiplier) + digit;
          ~~~~~^~~~~~~~~~~~~~
cc1: all warnings being treated as errors

initializing multiplier = 0 fixes the error